### ISSUE TITLE
Config URL scheme is invalid

### ISSUE THREAD

**Issue by durwa004** [LinkageIO/GitMirror#1]
It looks like the webhook isn't recognizing the URL - it says "This doesn't look like a valid URL".

I used Payload URL: rapidash.linkage.io:57283
Content type: application/json

I didn't change anything else.

**Comment by schae234** [comment]
I think i might have forgotten to add it needs be `http://rapidash.linkage.io:57283` with the proper `http://`

Note: we dont support `https://` .... yet
